Repository hacks/hacks.github.io, pull requests merged in 2020-06, with the labels that each got.

#67 Add message to feature yourself on People
  src/components/hacks-nav.vue
  src/styles/_default.scss
  src/styles/_variables.scss
  src/views/Members.vue
  src/views/Page.vue
Labels: design, update

#68 Added mobile & accessible changes
  src/assets/speech-bubble.svg
  src/components/hacks-nav.vue
  src/styles/_default.scss
  src/styles/_variables.scss
  src/views/About.vue
  src/views/EBoard.vue
  src/views/Home.vue
  src/views/Members.vue
Labels: bug, design

#71 Add ackee tracking
  package.json
  src/main.js
  yarn.lock
Labels: dependencies
